language: python

jobs:
  inlude:
    - name: "Python 3.8 on Xenial Linux - x86_64"
      python: 3.8
      dist: xenial
      arch: x86_64
    - name: "Python 3.8 on bionic Linux - x86_64"
      python: 3.8
      dist: bionic
      arch: x86_64

install:
  - pip3 install -r requirements.txt

script:
  - coverage run -m unittest discover
