language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

os:
  - linux
dist:
  - bionic

install:
  - pip3 install -r requirements.txt

script:
  - coverage run -m unittest discover
